apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp-chart.fullname" . }}-appsettings
data:
  appsettings.json: |-
    {
      "Setting1": "{{ .Values.appsettings.Setting1 }}",
      "Setting2": "{{ .Values.appsettings.Setting2 }}"
    }