apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "myapp-chart.fullname" . }}-cron
spec:
  schedule: "{{ .Values.cron.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron
              image: "{{ .Values.cron.image.repository }}:{{ .Values.cron.image.tag }}"
              imagePullPolicy: {{ .Values.cron.image.pullPolicy }}
              volumeMounts:
                - name: appsettings-volume
                  mountPath: /app/appsettings.json
                  subPath: appsettings.json
          volumes:
            - name: appsettings-volume
              configMap:
                name: {{ include "myapp-chart.fullname" . }}-appsettings
          restartPolicy: OnFailure