name: Build, Push, and Deploy with Helm

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate version tag
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo 'v0.0.0')
          COMMIT=$(git rev-parse --short HEAD)
          IMAGE_TAG="${VERSION}-${COMMIT}"
          CHART_VERSION="${VERSION}.${GITHUB_RUN_NUMBER}"
          echo "::set-output name=image_tag::$IMAGE_TAG"
          echo "::set-output name=chart_version::$CHART_VERSION"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${ github.actor }
          password: ${ secrets.GITHUB_TOKEN }

      - name: Build and push Web API image
        run: |
          docker build -t ghcr.io/PascalIcatt/mywebapi:${ '{' } steps.version.outputs.image_tag { '}' } -f MyWebApi/Dockerfile .
          docker push ghcr.io/PascalIcatt/mywebapi:${ '{' } steps.version.outputs.image_tag { '}' }

      - name: Build and push CronJob image
        run: |
          docker build -t ghcr.io/PascalIcatt/mycronjob:${ '{' } steps.version.outputs.image_tag { '}' } -f MyCronJob/Dockerfile .
          docker push ghcr.io/PascalIcatt/mycronjob:${ '{' } steps.version.outputs.image_tag { '}' }

      - name: Update Helm chart version
        run: |
          sed -i "s/^version:.*/version: ${ '{' } steps.version.outputs.chart_version { '}' }/" myapp-chart/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: ${ '{' } steps.version.outputs.image_tag { '}' }/" myapp-chart/Chart.yaml
          sed -i "s/tag: \"latest\"/tag: \"${ '{' } steps.version.outputs.image_tag { '}' }\"/" myapp-chart/values.yaml

      - name: Package and Publish Helm Chart
        run: |
          helm package myapp-chart --version ${ '{' } steps.version.outputs.chart_version { '}' }
          mkdir -p ./helm-charts
          mv myapp-chart-${ '{' } steps.version.outputs.chart_version { '}' }.tgz ./helm-charts/
          helm repo index ./helm-charts --url https://PascalIcatt.github.io/TestDeployRepo/

      - name: Publish Helm Chart to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${ '{' } secrets.GITHUB_TOKEN { '}' }
          publish_dir: ./helm-charts
          keep_files: true

      - name: Deploy with Helm
        run: |
          helm repo add myrepo https://PascalIcatt.github.io/TestDeployRepo/
          helm repo update
          helm upgrade --install myapp myrepo/myapp-chart --version ${ '{' } steps.version.outputs.chart_version { '}' } --atomic --timeout 300s
